import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';
import HeaderPage from '@/app/components/layout/Header/HeaderPage';

const robotoSans = Roboto({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable}`}>
        <HeaderPage />
        <main>{children}</main>
      </body>
    </html>
  );
}
