import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import HeaderPage from '@/app/components/layout/Header/HeaderPage';
import { StoreProvided } from '@/lib/providers/storeProvider';
import './globals.scss';

const robotoSans = Roboto({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable}`}>
        <StoreProvided>
          <HeaderPage />
          <main>{children}</main>
        </StoreProvided>
      </body>
    </html>
  );
}
